### ISSUE TITLE
interesting bug

### ISSUE THREAD

**Issue by tunnckoCore** [helpers/helper-related#1]
actually it's not a bug.
almost all tests fails. catch that when try to run my [npm-related cli](https://github.com/tunnckoCore/npm-related) which is based on this.. soo based on `get-pkgs` -> `package-json` and `registry-url`

```
related helper: getting related projects from npm.
helper-related: {"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"registry.npmjs.orgremarkable","host":"registry.npmjs.orgremarkable","port":443}
    2) should get an array of package.json files:
```

so one missing slash, lol
actually because @sindresorhus didn't run tests before publish lol and 3rd test fails https://github.com/sindresorhus/registry-url/blob/master/test.js#L37

https://github.com/sindresorhus/registry-url/issues/4

**Comment by kevva** [comment]
> actually because @sindresorhus didn't run tests before publish lol

lol. Travis succeeds, it succeeds locally for me and noone has reported any issues with this before you.

**Comment by tunnckoCore** [comment]
@kevva try to set registry like this

```
npm config set registry https://registry.npmjs.org
```

and try again, I figured it out, will PR

**Comment by kevva** [comment]
Yea, but that's more of a user error than @sindresorhus forgetting to run the tests before publishing, right?

**Comment by tunnckoCore** [comment]
nevermind, package should handle this :)

**Comment by tunnckoCore** [comment]
its not good thing to broke all chain because one simple normalize like this one

``` js
.replace(/\/$/, '') + '/'
```

or something more performant, nevermind

**Comment by jonschlinkert** [comment]
I like issues that resolve themselves lol

**Comment by sindresorhus** [comment]
> actually because @sindresorhus didn't run tests before publish lol and 3rd test fails

I'm actually not able to publish if tests are failing, since I use https://gist.github.com/sindresorhus/8435329

**Comment by jonschlinkert** [comment]
@tunnckoCore might be good practice to, I don't know, make 100% absolutely sure that you're right before you start at-mentioning the world in issues. just a thought

**Comment by tunnckoCore** [comment]
doh, yea, very sorry :)
