### ISSUE TITLE
truncate options not works correctly

### ISSUE THREAD

**Issue by tunnckoCore** [helpers/helper-related#2]
first use case

``` js
related(['micromatch'], {truncate: false}, function (err, res) {
  console.log(res);
  //=> '[micromatch](https://github.com/jonschlinkert/micromatch): '
});
```

and second use case when `truncate:true` truncates to first word, same also if more than one package given in array

``` js
related(['micromatch'], {truncate: false}, function (err, res) {
  console.log(res);
  //=> '[micromatch](https://github.com/jonschlinkert/micromatch): Glob… [more](https://github.com/jonschlinkert/micromatch)'
});
```

**Comment by tunnckoCore** [comment]
I thought
- when `truncate: false` it would be full description
- when `truncate: true` it would truncate to 15, because [L76](https://github.com/helpers/helper-related/blob/master/index.js#L76)
- when `words: number` it would truncate to `number`

**Comment by tunnckoCore** [comment]
yep, handled and added more tests, will PR - no breaking changes, works as you expect - truncate to 15 by default (when no options and only when truncate:false)

**Comment by jonschlinkert** [comment]
yeah, thanks. more testing around this would be great. I thought it was a nice idea, there is definitely room for improvement
