### ISSUE TITLE
using `filter-array` instead?

### ISSUE THREAD

**Issue by tunnckoCore** [helpers/helper-related#5]
started from here https://github.com/jonschlinkert/filter-array/pull/2#issuecomment-98273609

**Comment by tunnckoCore** [comment]
/cc @jonschlinkert 

this will allow the CLI to looks like

```
npm-related jstransformer-*css* --remove jstransformer-post*
npm-related npm-pkgs-* --remove npm-pkgs-filter
npm-related parser-* --remove parser-cac*
```

and so on

**Comment by tunnckoCore** [comment]
my fault, it is for `remove` option currently, but when i update `npm-pkgs` to work with npm registry api we can use it to allow globs for package names

**Comment by jonschlinkert** [comment]
ok, I'll merge this in as soon as I get a chance. thanks

**Comment by jonschlinkert** [comment]
btw, do you know of a way to get notifications back that were marked as `read`? I don't see anything in github or the API.

**Comment by tunnckoCore** [comment]
> ok, I'll merge this in as soon as I get a chance. 

yea, i understand you.

> btw, do you know of a way to get notifications back that were marked as read?

nope
